name: Build and publish docker image Dev

on:
  push:
    branches:
      - dev

env:
  NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
         OWNER: '${{ github.repository_owner }}'
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ing-sis-printscript-snippet-searcher
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        env:
          GITHUB_ACTOR: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          docker build -t ghcr.io/ing-sis-printscript-snippet-searcher/snippets-searcher-ui-dev:0.0.1 .
          docker push ghcr.io/ing-sis-printscript-snippet-searcher/snippets-searcher-ui-dev:0.0.1
          
          
  run_remote_script:
    name: Run remote script
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          chmod 600 ../private.key
          ssh-keyscan ${{secrets.DEV_SSH_HOST}} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Run script on remote machine
        run: |
          ssh -v -i ../private.key azureuser@${{secrets.DEV_SSH_HOST}} "~/deploy.sh"
